repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: debug-statements
      - id: name-tests-test
        args: [ "--django" ]
      - id: end-of-file-fixer
        exclude: .+/(fonts|css)/.+
      - id: trailing-whitespace
        exclude: .+/(fonts|css)/.+

  - repo: local
    hooks:
    - id: isort
      name: isort-local
      entry : isort
      language: python
      types: [python]
      exclude: .+/(settings.py|migrations)/.+
      pass_filenames: true
    - id: prospector
      name: prospector-local
      entry: prospector --messages-only
      language: python
      types: [python]
      exclude: ((.+/(settings.py|migrations)/.+)|^manage.py)
      pass_filenames: true
    - id: migrations-check
      language: system
      name: Check for uncreated migrations.
      entry: bash -c "./manage.py makemigrations --check --dry-run"
      types: ["python"]
      pass_filenames: false
    - id: django-test
      name: django-test
      entry: bash -c "pytest"
      language: system
