output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

uses:
  - django
  - celery

pep8:
  full: true
  options:
    max-line-length: 100

pylint:
  load-plugins:
    - pylint_django
  disable:
    - invalid-name
    - wrong-import-order
    - arguments-differ
  options:
    django-settings-module: githubmonitor.settings
    load-plugins: pylint_django
    max-line-length: 100

dodgy:
  run: true

ignore-paths:
  - node_modules
  - venv
  - env

ignore-patterns:
  - .+/migrations/.+
  - .+/settings.py
  - manage.py
